<?php

use Carbon\Carbon as Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Class UserTableSeeder
 */
class EavAttributeTableSeeder extends Seeder
{
    public function run()
    {
        if (env('DB_CONNECTION') == 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        }

        if (env('DB_CONNECTION') == 'mysql') {
            DB::table('eav_attribute')->truncate();
        } elseif (env('DB_CONNECTION') == 'sqlite') {
            DB::statement('DELETE FROM eav_attribute');
        } elseif (env('DB_CONNECTION') == 'mongodb') {
            DB::collection('eav_attribute')->delete();
        } else {
            //For PostgreSQL or anything else
            DB::statement('TRUNCATE TABLE eav_attribute CASCADE');
        }

        $eav = [
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'website_id',
                'backend_type'=>'static',
                'frontend_input'=>'select',
                'frontend_label'=>'Associate to Website',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'store_id',
                'backend_type'=>'static',
                'frontend_input'=>'select',
                'frontend_label'=>'Create In',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'created_in',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Created From',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'prefix',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Prefix',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'firstname',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'First Name',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'middlename',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Middle Name/Initial',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'lastname',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Last Name',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'suffix',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Suffix',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'email',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Email',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'group_id',
                'backend_type'=>'static',
                'frontend_input'=>'select',
                'frontend_label'=>'Group',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'dob',
                'backend_type'=>'static',
                'frontend_input'=>'date',
                'frontend_label'=>'Date of Birth',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'password_hash',
                'backend_type'=>'static',
                'frontend_input'=>'hidden',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'rp_token',
                'backend_type'=>'static',
                'frontend_input'=>'hidden',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'rp_token_created_at',
                'backend_type'=>'static',
                'frontend_input'=>'date',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'default_billing',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Default Billing Address',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'default_shipping',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Default Shipping Address',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'taxvat',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Tax/VAT Number',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'confirmation',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Is Confirmed',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'created_at',
                'backend_type'=>'static',
                'frontend_input'=>'date',
                'frontend_label'=>'Created At',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'gender',
                'backend_type'=>'static',
                'frontend_input'=>'select',
                'frontend_label'=>'Gender',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'disable_auto_group_change',
                'backend_type'=>'static',
                'frontend_input'=>'boolean',
                'frontend_label'=>'Disable Automatic Group Change Based on VAT ID',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'prefix',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Prefix',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'firstname',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'First Name',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'middlename',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Middle Name/Initial',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'lastname',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Last Name',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'suffix',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Suffix',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'company',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Company',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'street',
                'backend_type'=>'static',
                'frontend_input'=>'multiline',
                'frontend_label'=>'Street Address',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'city',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'City',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'country_id',
                'backend_type'=>'static',
                'frontend_input'=>'select',
                'frontend_label'=>'Country',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'region',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'State/Province',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'region_id',
                'backend_type'=>'static',
                'frontend_input'=>'hidden',
                'frontend_label'=>'State/Province',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'postcode',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Zip/Postal Code',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'telephone',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Phone Number',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'fax',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Fax',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'vat_id',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'VAT number',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'vat_is_valid',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'VAT number validity',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'vat_request_id',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'VAT number validation request ID',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'vat_request_date',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'VAT number validation request date',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'2',
                'attribute_code'=>'vat_request_success',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'VAT number validation request success',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'1',
                'attribute_code'=>'updated_at',
                'backend_type'=>'static',
                'frontend_input'=>'date',
                'frontend_label'=>'Updated At',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'name',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'Name',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'is_active',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Is Active',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'description',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Description',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'image',
                'backend_type'=>'varchar',
                'frontend_input'=>'image',
                'frontend_label'=>'Image',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'meta_title',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'Page Title',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'meta_keywords',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Meta Keywords',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'meta_description',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Meta Description',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'display_mode',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Display Mode',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'landing_page',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'CMS Block',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'is_anchor',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Is Anchor',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'path',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Path',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'position',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Position',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'all_children',
                'backend_type'=>'text',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'path_in_store',
                'backend_type'=>'text',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'children',
                'backend_type'=>'text',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'custom_design',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Custom Design',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'custom_design_from',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Active From',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'custom_design_to',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Active To',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'page_layout',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Page Layout',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'custom_layout_update',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Custom Layout Update',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'level',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Level',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'children_count',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Children Count',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'available_sort_by',
                'backend_type'=>'text',
                'frontend_input'=>'multiselect',
                'frontend_label'=>'Available Product Listing Sort By',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'default_sort_by',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Default Product Listing Sort By',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'include_in_menu',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Include in Navigation Menu',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'custom_use_parent_settings',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Use Parent Category Settings',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'custom_apply_to_products',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Apply To Products',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'filter_price_range',
                'backend_type'=>'decimal',
                'frontend_input'=>'text',
                'frontend_label'=>'Layered Navigation Price Step',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'name',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'Product Name',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'sku',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'SKU',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'description',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Description',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'short_description',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Short Description',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'price',
                'backend_type'=>'decimal',
                'frontend_input'=>'price',
                'frontend_label'=>'Price',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'special_price',
                'backend_type'=>'decimal',
                'frontend_input'=>'price',
                'frontend_label'=>'Special Price',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'special_from_date',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Special Price From Date',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'special_to_date',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Special Price To Date',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'cost',
                'backend_type'=>'decimal',
                'frontend_input'=>'price',
                'frontend_label'=>'Cost',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'weight',
                'backend_type'=>'decimal',
                'frontend_input'=>'weight',
                'frontend_label'=>'Weight',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'manufacturer',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Manufacturer',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'meta_title',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'Meta Title',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'meta_keyword',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Meta Keywords',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'meta_description',
                'backend_type'=>'varchar',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Meta Description',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'image',
                'backend_type'=>'varchar',
                'frontend_input'=>'media_image',
                'frontend_label'=>'Base',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'small_image',
                'backend_type'=>'varchar',
                'frontend_input'=>'media_image',
                'frontend_label'=>'Small',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'thumbnail',
                'backend_type'=>'varchar',
                'frontend_input'=>'media_image',
                'frontend_label'=>'Thumbnail',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'media_gallery',
                'backend_type'=>'static',
                'frontend_input'=>'gallery',
                'frontend_label'=>'Media Gallery',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'old_id',
                'backend_type'=>'int',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'tier_price',
                'backend_type'=>'decimal',
                'frontend_input'=>'text',
                'frontend_label'=>'Tier Price',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'color',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Color',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'news_from_date',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Set Product as New from Date',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'news_to_date',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Set Product as New to Date',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'gallery',
                'backend_type'=>'varchar',
                'frontend_input'=>'gallery',
                'frontend_label'=>'Image Gallery',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'status',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Enable Product',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'minimal_price',
                'backend_type'=>'decimal',
                'frontend_input'=>'price',
                'frontend_label'=>'Minimal Price',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'visibility',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Visibility',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'custom_design',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'New Theme',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'custom_design_from',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Active From',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'custom_design_to',
                'backend_type'=>'datetime',
                'frontend_input'=>'date',
                'frontend_label'=>'Active To',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'custom_layout_update',
                'backend_type'=>'text',
                'frontend_input'=>'textarea',
                'frontend_label'=>'Layout Update XML',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'page_layout',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Layout',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'category_ids',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>'Categories',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'options_container',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Display Product Options In',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'required_options',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'has_options',
                'backend_type'=>'static',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'image_label',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'Image Label',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'small_image_label',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'Small Image Label',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'thumbnail_label',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'Thumbnail Label',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'created_at',
                'backend_type'=>'static',
                'frontend_input'=>'date',
                'frontend_label'=>null,'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'updated_at',
                'backend_type'=>'static',
                'frontend_input'=>'date',
                'frontend_label'=>null,'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'country_of_manufacture',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Country of Manufacture',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'quantity_and_stock_status',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Quantity',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'custom_layout',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'New Layout',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'msrp',
                'backend_type'=>'decimal',
                'frontend_input'=>'price',
                'frontend_label'=>'Manufacturer\'s Suggested Retail Price',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'msrp_display_actual_price_type',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Display Actual Price',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'url_key',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'URL Key',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'3',
                'attribute_code'=>'url_path',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'url_key',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>'URL Key',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'url_path',
                'backend_type'=>'varchar',
                'frontend_input'=>'text',
                'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'links_purchased_separately',
                'backend_type'=>'int',
                'frontend_input'=>null,'frontend_label'=>'Links can be purchased separately',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'samples_title',
                'backend_type'=>'varchar',
                'frontend_input'=>null,'frontend_label'=>'Samples title',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'links_title',
                'backend_type'=>'varchar',
                'frontend_input'=>null,'frontend_label'=>'Links title',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'links_exist',
                'backend_type'=>'int',
                'frontend_input'=>null,'frontend_label'=>null,'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'price_type',
                'backend_type'=>'int',
                'frontend_input'=>'boolean',
                'frontend_label'=>null,'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'sku_type',
                'backend_type'=>'int',
                'frontend_input'=>'boolean',
                'frontend_label'=>null,'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'weight_type',
                'backend_type'=>'int',
                'frontend_input'=>'boolean',
                'frontend_label'=>null,'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'price_view',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Price View',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'shipment_type',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Ship Bundle Items',
                'is_required'=>'1',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'swatch_image',
                'backend_type'=>'varchar',
                'frontend_input'=>'media_image',
                'frontend_label'=>'Swatch',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'tax_class_id',
                'backend_type'=>'int',
                'frontend_input'=>'select',
                'frontend_label'=>'Tax Class',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'entity_type_id'=>'4',
                'attribute_code'=>'gift_message_available',
                'backend_type'=>'varchar',
                'frontend_input'=>'select',
                'frontend_label'=>'Allow Gift Message',
                'is_required'=>'0',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ]
        ];

        DB::table('eav_attribute')->insert($eav);

        if (env('DB_CONNECTION') == 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }
    }
}